name: flashcards_app
description: A Flutter flashcards app with projects/folders and practice mode.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  path_provider: ^2.0.14
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/flashquanta_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/flashquanta_logo.png"